env:
  es6: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:import/errors
  - plugin:import/warnings
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
  - import
settings:
  import/resolver:
    typescript: '.'
rules:
  import/prefer-default-export: off
  no-useless-constructor: 0
  no-new: 0
  '@typescript-eslint/no-unused-vars': error
